source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BoxesView_Example', :exclusive => true do
  pod 'BoxesView', :path => '../'
end

target 'BoxesView_Tests', :exclusive => true do
  pod 'BoxesView', :path => '../'

  
end
